spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-dev
server: 
  port: 7788

---
spring:
  profiles: test
  application:
    name: spring-cloud-config-test
server: 
  port: 7789
